# Site settings
title: al-pez
description: al-pez github page
baseurl: /
url: https://al-pez.github.io/

# User settings
username: Alex Perez
user_description: This is just a small selection of the toys I like to play with. Love to share new ways of creating software, and always eager to discover any new technology that pops around (amazes me the feeling of brain-expansion when something new falls into your hands)
user_title: Software Developer
email: alexperez.dec@gmail.com.com
twitter_username: nah
github_username:  al-pez
gplus_username:  nah

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
